# Generated by Django 5.1.2 on 2024-12-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cagliaritour", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="average_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="num_negative_comments",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="num_positive_comments",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="user_rating_accessibility",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="wheelchair_accessible_entrance",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="QValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("nationality", models.CharField(max_length=50)),
                ("interests", models.JSONField()),
                ("action", models.JSONField()),
                ("q_value", models.FloatField(default=0)),
            ],
            options={
                "unique_together": {("age", "nationality", "interests", "action")},
            },
        ),
    ]
